## trabalhando com blibiottecas 
# math é uma biblioteca matematica
# uma biblioteca é um acervo de codigos prontos em que podemos usar
# para otimizar e potencializar nossa codificação 

import math # importando a biblioteca math para o codigo 

#math.ceil() é usada para arredondar valores

a = math.ceil(8.5)
print('arredondar',a)


##math.sqrt >> ela vai trazer a rai qudrada de um numero

b = math.sqrt(25)
print(' raiza quadrada', b)

##

# -*- coding: utf-8 -*-
"""aula07pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-1Bjo-r4i4HOY3ye63ozxaUdB-AULVo

Importando o pandas
"""

import pandas as pd
import string as st





"""trabalhando com series

"""

lista = ([4, 5 ,6 ,8,10])

serieA = pd.Series(lista)

serieA

serieA = pd.Series (lista, index = ['a', 'b', 'c', 'd','e'])

serieA

num = 0
listaIndex = []
for i in lista:
  num = num + 1
  listaIndex.append(f'a{num}')

listaIndex

serieA = pd.Series(lista, index = listaIndex)

serieA

alfabeto = list(st.ascii_lowercase)

for i in range(30):
  if i <=26:
    nova_letra = f'{alfabeto[i]}1'
  else:
    nova_letra = f'{alfabeto[i]}2'
alfabeto.append(nova_letra)

print(alfabeto)

indiceAlfabeto = []
for i in range(len(lista)):
  indiceAlfabeto.append(alfabeto[i])

indiceAlfabeto

SerieA = pd.Series(lista, index= indiceAlfabeto)

serieA

